[[proxy]]
host = "website.local.gd"
socket = true
target = "./www.sock"
[proxy.spawn]
command = "/usr/bin/node"
args = [ "./webserver/index.mjs" ]
envs = [ ["PORT", "www.sock"] ]

[[proxy]]
host = "git.local.gd"
target = "http://192.168.0.3:80"