listen = "[::]:3000"

[[proxy]]
hosts = [ "website.local.gd", "website-alt.local.gd" ]
socket = true
target = "./www.sock"
[proxy.spawn]
command = "/usr/bin/node"
args = [ "./webserver/index.mjs" ]
envs = [ ["PORT", "www.sock"] ]

[[proxy]]
hosts = [ "git.local.gd" ]
target = "http://192.168.0.3:80"